version: "3"

services:
  redis_master:
    image: redis:latest
    container_name: redis_master
    command: bash -c "redis-server --appendonly yes --requirepass pass"
    ports:
      - "6379:6379"
    networks:
      - redis-replication
    volumes:
      - "./data:/data"

  redis_slave:
    image: redis:latest
    container_name: redis_slave
    command: redis-server /etc/redis.conf --replicaof redis_master 6379
    ports:
      - "6380:6379"
    depends_on:
      - redis_master
    volumes:
      - ./redis.conf:/etc/redis.conf

    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge
